sudo: required
dist: bionic
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - zeroc-ice
            - libzeroc-ice-dev
            - slice2cpp
            - libopencv-dev
            - libgsl0-dev
            - libopenscenegraph-dev
            - freeglut3-dev
            - libboost-system-dev
            - libboost-thread-dev
            - qt4-dev-tools
            - pyside-tools
            - libxt-dev
            - pyqt4-dev-tools
            - libboost-all-dev
            - libccd
            - libccd-dev
            - libflann-dev

      env: COMPILER=g++

before_install:
  - sudo apt-get update -qq
# Commands to try and fix check failures
#  - sudo rm /var/lib/apt/lists/lock
#  - sudo rm /var/cache/apt/archives/lock
#  - sudo rm /var/lib/dpkg/lock

script:
  - export ROBOCOMP="/home/travis/build/robocomp/robocomp"
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DFCL_SUPPORT=1 . && make
