# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Robocomp

description: Robotics Framework
author:
  name: Robocomp
  email: ljmanso@unex.es
  github: robocomp
  twitter: 
  pinterest: 
  linkedin: 
  bio: Robotics Framework
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: /robocomp
